version: "3.8"
services:
  grafana:
    image: grafana/grafana:8.1.3
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
    - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=orginsights-s3-datasource
    - GF_PLUGINS_ENABLE_ALPHA=true
    volumes:
    - /Users/itay/private/plugins:/var/lib/grafana/plugins
    - ./docker/config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
    - "3000:3000"
  minio-init:
    image: minio/mc
    environment:
    - S3_ENDPOINT=http://minio:9000
    - MINIO_ACCESS_KEY=minioadmin
    - MINIO_SECRET_KEY=minioadmin
    - BUCKET=my-bucket
    volumes:
    - ./insertion.sh:/insertion.sh
    entrypoint: /insertion.sh
  minio:
    image: minio/minio:RELEASE.2021-09-09T21-37-07Z
    ports: 
    - 9000:9000
    - 9001:9001
    command: server /data --console-address ":9001"